{% set name = "ecos" %}
{% set version = "2.0.7.post1" %}
{% set sha256 = "83e90f42b3f32e2a93f255c3cfad2da78dbd859119e93844c45d2fca20bdc758" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 1
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  skip: true  # [py27 and (ppc64le or aarch64)]

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - python
    - pip
    - mkl-devel  # [blas_impl == "mkl"]
    - openblas-devel  # [blas_impl == "openblas"]
    - numpy
  run:
    - python
    - {{ pin_compatible('numpy') }}
    - scipy >=0.9

test:
  imports:
    - ecos
    - _ecos
  files:
    - test_interface_bb.py  # copied from repo; isn't in the sdist
  commands:
    - python test_interface_bb.py

about:
  home: http://www.embotech.com/ECOS
  license: GPL-3.0
  license_family: GPL
  license_file: LICENSE  # in recipe for now; https://github.com/embotech/ecos-python/pull/15
  summary: 'Python interface for ECOS, a lightweight conic solver for second-order cone programming'
  dev_url: https://github.com/embotech/ecos-python

extra:
  recipe-maintainers:
    - dougalsutherland
